# Generated by Django 5.2.17 on 2026-10-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Perro'), ('cat', 'Gato'), ('bird', 'Ave'), ('other', 'Otro')], default='dog', max_length=20)),
                ('age', models.IntegerField(help_text='Edad en años')),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Macho'), ('female', 'Hembra')], default='male', max_length=20)),
                ('img', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('availableForAdoption', models.BooleanField(default=True)),
            ],
        ),
    ]
